version: "3.8"
services:
  primary:
    image: percona/percona-server:8.0
    command: --server-id=1 --log-bin --log-replica-updates --gtid_mode=on --enforce-gtid-consistency
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306
    volumes:
      - ./init-primary.sql:/docker-entrypoint-initdb.d/init-primary.sql:ro
  replica:
    image: percona/percona-server:8.0
    command: --server-id=2 --log-bin --log-replica-updates --gtid_mode=on --enforce-gtid-consistency --read_only=ON
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3307:3306
    volumes:
      - ./init-replica.sql:/docker-entrypoint-initdb.d/init-replica.sql:ro
  gh-ost:
    build:
      args:
        GIT_TAG: ${GIT_TAG}
    command: |
      -user root \
      -host replica \
      -assume-master-host primary \
      -throttle-control-replicas=replica:3306 \
      -database test \
      -table testtable \
      -alter 'ENGINE=InnoDB' \
      -exact-rowcount \
      -concurrent-rowcount \
      -postpone-cut-over-flag-file /tmp/postpone.flag \
      -verbose
    volumes:
      - ./postpone.flag:/tmp/postpone.flag:ro
    depends_on:
      - primary
      - replica
