version: "3.8"
services:
  primary:
    image: percona/percona-server:8.0
    command: --server-id=1 --log-bin --log-replica-updates --gtid_mode=on --enforce-gtid-consistency --port=3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306
    volumes:
      - ./init-primary.sql:/docker-entrypoint-initdb.d/init-primary.sql:ro
  replica:
    image: percona/percona-server:8.0
    command: --server-id=2 --log-bin --log-replica-updates --gtid_mode=on --enforce-gtid-consistency --port=3307 --read_only=ON
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3307:3307
    volumes:
      - ./init-replica.sql:/docker-entrypoint-initdb.d/init-replica.sql:ro
    depends_on:
      - primary
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy
    command: -host=0.0.0.0 -config /toxiproxy.json -proxy-metrics
    expose:
      - 3306
      - 3307
      - 8474
    ports:
      - 8474:8474
    volumes:
      - ./toxiproxy.json:/toxiproxy.json:ro
    depends_on:
      - primary
      - replica
  gh-ost:
    build:
      args:
        GIT_TAG: ${GIT_TAG}
    command: |
      -user root \
      -host toxiproxy \
      -port 3307 \
      -assume-master-host 'toxiproxy:3306' \
      -throttle-control-replicas 'toxiproxy:3307' \
      -database test \
      -table testtable \
      -alter 'ENGINE=InnoDB' \
      -exact-rowcount \
      -concurrent-rowcount \
      -max-load 'Threads_running=50' \
      -critical-load 'Threads_running=100' \
      -critical-load-hibernate-seconds 90 \
      -postpone-cut-over-flag-file /tmp/postpone.flag \
      -verbose
    volumes:
      - ./postpone.flag:/tmp/postpone.flag:ro
    depends_on:
      - primary
      - replica
      - toxiproxy
