ghostbuster: test container {
  ghostblaster: ghostblaster
  gh-ost: gh-ost
}

toxiproxy: {
  primary: :3306\n(primary)
  replica: :3307\n(replica)
}

ghostbuster -> toxiproxy: REST API {
  style.stroke-dash: 3
}
ghostbuster.gh-ost -> toxiproxy.primary: MySQL\n(applier)
ghostbuster.gh-ost -> toxiproxy.replica: MySQL\n(inspector)

primary: {
  shape: cylinder
}
replica: {
  shape: cylinder
}

ghostbuster.ghostblaster -> primary: MySQL {
  style.stroke-dash: 3
}
toxiproxy.primary -> primary: MySQL
toxiproxy.replica -> replica: MySQL
